name: Bug Report
about: Report a bug
title: "[BUG] Title here"
labels: bug
assignees: ''
---

**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
What did you expect to happen?

**Steps to reproduce**
Please describe the steps to reproduce the issue.

**Additional context**
Any other info to help diagnose the problem.
