name: Feature Request
about: Suggest a new feature for Tailored
title: "[FEATURE] Title here"
labels: enhancement
assignees: ''

---

**Is your feature request relate to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Additional context**
Add any other context or screenshots about the feature request here.
